version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    ports:
        - "9090:9090"
    networks:
      metrics-net:
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    restart: always
    ports:
        - "3000:3000"
    networks:
      metrics-net:
networks:
  metrics-net:
