version: '3'
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    restart: always
    ports:
        - "3000:3000"
    networks:
      metrics-net:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
        - "8086:8086"
    networks:
        - metrics-net
    volumes:
        - ./influxdb-storage:/vol01/Docker/monitoring
    environment:
        - INFLUXDB_DB=pellets
        - INFLUXDB_USER=admin
        - INFLUXDB_ADMIN_ENABLED=true
networks:
  metrics-net:
