version: '3'
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    restart: always
    ports:
        - "3055:3000"
    networks:
      metrics-net:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
        - "8086:8086"
    networks:
        - metrics-net
    volumes:
        - ./influxdb-storage:/var/lib/influxdb
        - ./influxdb-backup:/backup
    environment:
        - INFLUXDB_DB=pellets
        - INFLUXDB_USER=admin
        - INFLUXDB_ADMIN_ENABLED=true
  crawler:
    container_name: pellet-crawler
    build:
      dockerfile: Dockerfile
      context: ./crawler
    depends_on:
      - influxdb
    networks:
        - metrics-net
    volumes:
      - ./crawler:/app
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=pellets
      - INFLUXDB_USER=admin
      - INFLUXDB_PASS=
    restart: always
networks:
  metrics-net:
